# Config file for automatic testing at travis-ci.com

language: python
python:
  - 3.8
  - 3.7

install: pip install -r requirements_dev.txt && pip install -e .

# Command to run tests, e.g. python setup.py test
script: py.test -v tests
